### ISSUE TITLE
Supplementary Tables

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/DLPFC_snRNAseq#24]
- [ ] Merge demographics + cellranger metrics + pre-sequencing metrics + QC metrics (number dropped, pre-emptyDroplets number, discarded by x or y reason, etc)

- [x]  Annotation details (cor values if around)

**Comment by lcolladotor** [comment]
Use https://github.com/LieberInstitute/DLPFC_snRNAseq/blob/9bc324540fd66b6adf1c00da7587d8d99516399a/code/02_cellranger_metrics/03_combine_metrics.R#L68 to get the cell ranger metrics. You can leave the demographics alone since we have that already for these subjects.

So well, just merge the cellranger metrics with the other metrics to complete this table.
